### ISSUE TITLE
Friends can't see the device?

### ISSUE THREAD

**Issue by LeonZBaker** [Gloveman23/ScrapButton#1]
as the host I can see it on their POV's but they keep telling me that they can't see/don't know what I'm talking about, they have the same modpack/profile as me so I'm not too sure if its a mod issue or a me issue.

**Comment by Gloveman23** [comment]
This sounds like it may just not be installed correctly on their devices. Try having them update/reinstall. If that doesn't work, please provide your BepInEx log, and ideally one of theirs as well. Closing for now.

**Comment by Gloveman23** [comment]
There was an issue where the network prefab did not get registered, causing the object to only appear on the host. It has now been fixed. Thank you for pointing it out.
